---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks
# xxx.png: https://github.com/walkxcode/dashboard-icons/tree/main/png
# mdi-xxx.png: https://pictogrammers.com/library/mdi/
# si-xxx.png: https://simpleicons.org/

- Developer:
    - Github:
        - icon: github-light.png
          href: https://github.com/
    - StackOverflow:
        - icon: si-stackoverflow
          href: https://stackoverflow.com/
    - LeetCode:
        - icon: si-leetcode
          href: https://leetcode.com/

- Social:
    - Reddit:
        - icon: reddit.png
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - icon: youtube.png
          href: https://youtube.com/
