---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Mostly Used:
    - Notion:
        href: https://notion.so
        icon: notion.png
        description: Docs
    - ChatGpt:
        href: https://chat.openai.com/
        icon: si-openai
        description: ChatGpt

- Learning:
    - Udemy:
        href: https://www.udemy.com/
        icon: udemy.png
        description: Online Learning
    - Magoosh:
        href: https://ieltsgt.magoosh.com/dashboard
        icon: https://ieltsgt.magoosh.com/favicon-32x32.png
        description: IELTS
    - Coursera:
        href: https://www.coursera.org/
        icon: si-coursera

- Tools:
    - Longman:
        href: https://www.ldoceonline.com/
        icon: https://www.ldoceonline.com/external/images/logo_home_smartphone.svg?version=1.2.64
        description: Dictionary
    - YaHoo Japan:
        href: https://chiebukuro.yahoo.co.jp/
        icon: si-yahoo
    - Speed Test:
        href: https://www.speedtest.net/
        icon: si-speedtest

- News:
    - BBC News:
        href: https://www.bbc.com/news
        icon: si-bbc
    - BBC Sounds:
        href: https://www.bbc.co.uk/sounds/play/live:bbc_world_service
        icon: si-bbc
    - Science Daily:
        href: https://www.sciencedaily.com/
        icon: https://www.sciencedaily.com/favicon.ico
    - TED:
        href: https://www.ted.com/
        icon: si-ted
    - This I Believe:
        href: https://thisibelieve.org/essays/featured/
    - British Council:
        href: https://learnenglish.britishcouncil.org/skills/listening
        icon: https://learnenglish.britishcouncil.org/sites/podcasts/themes/bc_ui/logo.svg
    - ABC News:
        href: https://www.abc.net.au/
        icon: https://www.abc.net.au/core-assets/core/favicon-32x32.png
    - Elllo:
        href: https://elllo.org/archive/
